### ISSUE TITLE
Disappear Task when completed

### ISSUE THREAD

**Issue by gmfacundo** [FernandoAMartinez/BlazorToDo#6]
Make task disappear when is marked as completed

**Comment by FernandoAMartinez** [comment]
Now the `TaskComponent `has implemented an `EventCallback ` parameter, so when finishing an action (Archive, Complete) it calls `refreshListCallback.InvokeAsync()` method to trigger the parent component's `StateHasChange `method.
This result in the update of the lists at Pending, Archived and Completed Tasks List, .
